# Generated by Django 3.1.3 on 2020-11-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='udername',
            new_name='username',
        ),
    ]
