# Generated by Django 3.1.3 on 2020-11-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20201115_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['username']},
        ),
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('photo', models.TextField()),
                ('article_image', models.ImageField(default="url_for('image.jpg')", upload_to='articles/')),
                ('category', models.ManyToManyField(to='photos.category')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.editor')),
            ],
        ),
    ]
