# Generated by Django 3.1.3 on 2020-11-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201115_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='photo',
        ),
        migrations.AddField(
            model_name='pictures',
            name='photo_image',
            field=models.ImageField(default="url_for('image.jpg')", upload_to='photos/'),
        ),
    ]
