# Generated by Django 3.1.3 on 2020-11-17 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20201115_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photo_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
