# Generated by Django 3.1.3 on 2020-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20201117_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='info',
            field=models.TextField(default='picture details', max_length=255),
        ),
    ]
